package demosrv

const (
	SF_ICONIMAGE  string = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIAAQMAAADOtka5AAAAA1BMVEW2CBS0quENAAAAOklEQVR42uzAgQAAAADCsPypA/k2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC4BwAA//+CAAABkU5ASAAAAABJRU5ErkJggg==`
)
